# Generated by Django 3.0.4 on 2024-06-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SPX', models.FloatField()),
                ('USO', models.FloatField()),
                ('SLV', models.FloatField()),
                ('EUR_USD', models.FloatField()),
                ('GOLD', models.FloatField()),
            ],
        ),
    ]
